# Analiza drzava kroz vrijeme

URL https://raw.githubusercontent.com/plotly/datasets/master/gapminderDataFiveYear.csv
Data set koji prikazuje podatke po drzavama kroz vrijeme:
- drzava - country,
- godina mjerenja - year,
- broj stanovnik - pop,
- kontinent - continent,
- ocekivani zivotni vijek - lifeExp,
- BDP po stanovniku - gdpPercap


**Pitanje**: Postoji li povezanost izmedu BDP-a po stanovniku i ocekivanog zivotnog vijeka te kako se ti pokayatelji (rezultati analize) mijenjau kroz vrijeme?

Koristiti Pandas, NumPy i Matplotlib ili druge Data Science biblioteka po zelji (trebat ce pojasniti zasto i kako se koristi).

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/gapminderDataFiveYear.csv')
df.head()

       country  year         pop continent  lifeExp   gdpPercap
0  Afghanistan  1952   8425333.0      Asia   28.801  779.445314
1  Afghanistan  1957   9240934.0      Asia   30.332  820.853030
2  Afghanistan  1962  10267083.0      Asia   31.997  853.100710
3  Afghanistan  1967  11537966.0      Asia   34.020  836.197138
4  Afghanistan  1972  13079460.0      Asia   36.088  739.981106

In [7]:
df.shape

(1704, 6)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    1704 non-null   str
 1   year       1704 non-null   int64
 2   pop        1704 non-null   float64
 3   continent  1704 non-null   str
 4   lifeExp    1704 non-null   float64
 5   gdpPercap  1704 non-null   float64
dtypes: float64(3), int64(1), str(2)
memory usage: 80.0 KB

In [9]:
df.isna().sum()

country      0
year         0
pop          0
continent    0
lifeExp      0
gdpPercap    0
dtype: int64

In [10]:
df.describe()

             year           pop      lifeExp      gdpPercap
count  1704.00000  1.704000e+03  1704.000000    1704.000000
mean   1979.50000  2.960121e+07    59.474439    7215.327081
std      17.26533  1.061579e+08    12.917107    9857.454543
min    1952.00000  6.001100e+04    23.599000     241.165876
25%    1965.75000  2.793664e+06    48.198000    1202.060309
50%    1979.50000  7.023596e+06    60.712500    3531.846988
75%    1993.25000  1.958522e+07    70.845500    9325.462346
max    2007.00000  1.318683e+09    82.603000  113523.132900

In [12]:
df.year.max()

np.int64(2007)

In [13]:
df = df.rename(
    columns={
        'country': 'drzava',
        'year': 'godina',
        'pop': 'stanovnistvo',
        'continent': 'kontinent',
        'lifeExp': 'zivotni_vijek',
        'gdpPercap': 'bdp_po_stanovniku'
    }
)

df.head()

,drzava,godina,stanovnistvo,kontinent,zivotni_vijek,bdp_po_stanovniku
0,Afghanistan,1952,8425333.0,Asia,28.801,779.445314
1,Afghanistan,1957,9240934.0,Asia,30.332,820.853030
2,Afghanistan,1962,10267083.0,Asia,31.997,853.100710
3,Afghanistan,1967,11537966.0,Asia,34.020,836.197138
4,Afghanistan,1972,13079460.0,Asia,36.088,739.981106

In [14]:
nelogicne_vrijednosti = df[
    (df['stanovnistvo'] <= 0) |
    (df['bdp_po_stanovniku'] <= 0) |
    (df['zivotni_vijek'] <= 0)
]

nelogicne_vrijednosti

Empty DataFrame
Columns: [drzava, godina, stanovnistvo, kontinent, zivotni_vijek, bdp_po_stanovniku]
Index: []

In [15]:
df.godina.min(), df.godina.max()

(np.int64(1952), np.int64(2007))

In [16]:
df.kontinent.unique()

<StringArray>
['Asia', 'Europe', 'Africa', 'Americas', 'Oceania']
Length: 5, dtype: str

In [21]:
df.drzava.nunique()

142